export const widgetDevelopmentPlatforms = [
  { id: "whoop", label: "WHOOP" },
  { id: "apple", label: "Apple" },
  { id: "garmin", label: "Garmin" },
  { id: "oura", label: "Oura" },
] as const

export type WidgetDevelopmentPlatformId = (typeof widgetDevelopmentPlatforms)[number]["id"]
export type WidgetDevelopmentVisual = "score" | "line" | "bars" | "zones" | "ring" | "sleep" | "workout" | "cycle"
export type WidgetDevelopmentTone = "emerald" | "red" | "orange" | "amber" | "blue" | "cyan" | "purple" | "pink"

export interface WidgetDevelopmentMetric {
  id: string
  label: string
  shortLabel: string
  primaryValue: string
  secondaryValue: string
  detail: string
  visual: WidgetDevelopmentVisual
  tone: WidgetDevelopmentTone
  series: number[]
}

export const widgetDevelopmentMetrics: WidgetDevelopmentMetric[] = [
  {
    id: "full-day-hr",
    label: "Full-Day HR Graph / HR Data",
    shortLabel: "Heart Rate",
    primaryValue: "72 bpm",
    secondaryValue: "48-164 bpm",
    detail: "Full day range",
    visual: "line",
    tone: "red",
    series: [34, 38, 44, 78, 52, 46, 88, 62, 40, 36],
  },
  {
    id: "activity-hr-graph",
    label: "Activity HR Graph + Zones",
    shortLabel: "Workout HR",
    primaryValue: "148 bpm",
    secondaryValue: "HR graph + zones",
    detail: "Workout intensity",
    visual: "line",
    tone: "red",
    series: [40, 55, 76, 84, 70, 92, 88, 78, 62, 48],
  },
  {
    id: "resting-hr",
    label: "Resting HR",
    shortLabel: "Resting HR",
    primaryValue: "49 bpm",
    secondaryValue: "Within range",
    detail: "7-day avg",
    visual: "line",
    tone: "red",
    series: [52, 51, 50, 48, 49, 50, 49],
  },
  {
    id: "hrv-status",
    label: "HRV / HRV Status",
    shortLabel: "HRV",
    primaryValue: "68 ms",
    secondaryValue: "Balanced",
    detail: "Overnight",
    visual: "line",
    tone: "emerald",
    series: [54, 58, 61, 57, 66, 72, 68],
  },
  {
    id: "calories-active-energy",
    label: "Calories / Active Energy",
    shortLabel: "Energy",
    primaryValue: "742 cal",
    secondaryValue: "Active",
    detail: "Today",
    visual: "ring",
    tone: "red",
    series: [68],
  },
  {
    id: "weight",
    label: "Weight",
    shortLabel: "Weight",
    primaryValue: "176.8 lb",
    secondaryValue: "-1.2 lb",
    detail: "30-day trend",
    visual: "line",
    tone: "blue",
    series: [78, 76, 77, 74, 73, 72, 71],
  },
  {
    id: "vo2-max",
    label: "VO2 Max / Cardio Capacity",
    shortLabel: "VO2 Max",
    primaryValue: "53.4",
    secondaryValue: "High",
    detail: "Cardio fitness",
    visual: "score",
    tone: "purple",
    series: [77],
  },
  {
    id: "total-sleep-time",
    label: "Sleep Report",
    shortLabel: "Sleep Report",
    primaryValue: "7h 42m",
    secondaryValue: "Stages + duration",
    detail: "Last night",
    visual: "sleep",
    tone: "purple",
    series: [32, 45, 28, 36],
  },
  {
    id: "sleep-hours",
    label: "Sleep Time",
    shortLabel: "Sleep Time",
    primaryValue: "7.7 h",
    secondaryValue: "7-day avg",
    detail: "Sleep trend",
    visual: "bars",
    tone: "purple",
    series: [71, 80, 68, 77, 83, 74, 76],
  },
  {
    id: "sleep-score",
    label: "Sleep Score",
    shortLabel: "Sleep Score",
    primaryValue: "84",
    secondaryValue: "Good",
    detail: "Last night",
    visual: "score",
    tone: "purple",
    series: [84],
  },
  {
    id: "respiratory-rate",
    label: "Respiratory Rate / Respiration",
    shortLabel: "Respiration",
    primaryValue: "14.2",
    secondaryValue: "br/min",
    detail: "Overnight avg",
    visual: "line",
    tone: "cyan",
    series: [44, 46, 43, 45, 48, 46, 44],
  },
  {
    id: "training-load",
    label: "Strain / Activity Load / Training Load",
    shortLabel: "Training Load",
    primaryValue: "15.8",
    secondaryValue: "High",
    detail: "Today",
    visual: "score",
    tone: "orange",
    series: [79],
  },
  {
    id: "recovery-readiness",
    label: "Recovery Score / Readiness Summary",
    shortLabel: "Readiness",
    primaryValue: "72",
    secondaryValue: "Ready",
    detail: "Morning score",
    visual: "score",
    tone: "emerald",
    series: [72],
  },
  {
    id: "cycle-tracking",
    label: "Cycle Tracking",
    shortLabel: "Cycle",
    primaryValue: "Day 18",
    secondaryValue: "Luteal",
    detail: "Current phase",
    visual: "cycle",
    tone: "pink",
    series: [64],
  },
  {
    id: "full-workout-report",
    label: "Full Workout Report",
    shortLabel: "Workout Report",
    primaryValue: "Tempo Run",
    secondaryValue: "48 min - 148 avg HR",
    detail: "5.8 mi",
    visual: "workout",
    tone: "red",
    series: [42, 56, 75, 82, 76, 68, 61],
  },
  {
    id: "temperature-deviation",
    label: "Skin / Wrist / Body Temperature / Temperature Deviation",
    shortLabel: "Temperature",
    primaryValue: "+0.4 F",
    secondaryValue: "Above baseline",
    detail: "Overnight",
    visual: "line",
    tone: "orange",
    series: [38, 40, 44, 51, 58, 52, 48],
  },
  {
    id: "blood-oxygen",
    label: "Blood Oxygen / SpO2",
    shortLabel: "Blood Oxygen",
    primaryValue: "97%",
    secondaryValue: "SpO2",
    detail: "Overnight avg",
    visual: "bars",
    tone: "cyan",
    series: [96, 98, 97, 95, 97, 98, 97],
  },
]
